#== Reconstruction settings
num_subsets: [36, 24]
num_epochs: 10
initial_step_size: 1
update_interval: 96
relaxation_eta: 0.002
use_scatter: true
variance_reduction: "svrg" # can be "svrg", "saga", or "none"

#== Regularisation
no_prior: false
use_kappa: false
delta: null # smoothing parameter for TNV / TV
dynamic_percentile: 99.9  # Percentile for computing dynamic ranges
delta_divisor: 5.0
epsilon_divisor: 10.0  # Epsilon = dynamic_range / divisor (for log TNV)
prior_updates_per_epoch: null
snapshot_interval_factor: 1.0  # Update SVRG snapshot every epoch (was 2x)
precond_type: "mm_block_diag"

# Modality-specific TV prior settings
use_modality_specific_priors: false
prior: "tv" # can be tv or rdp
gamma_pet: 0.02
gamma_spect: 0.02
tv_stencil: "6" # can be 6, 18, or 26
tv_max_step: 1
tv_bnd_cond: "Neumann"
directional_tv: true
tv_both_directions: false

# TNV (vectorial) prior settings
use_tnv_prior: true
gamma_tnv: 1.0
alpha: 0.2
beta: 0.2
use_log_tnv: true  # Set to true to use log-domain TNV
tnv_stencil: "6"
tnv_max_step: 1
tnv_bnd_cond: "Neumann"
directional_tnv: true
tnv_both_directions: false
tail_singular_values: null
stable: false
smoothing: 'charbonnier' # can be charbonnier, fair or perona_malik

#== Image processing
pet_gauss_fwhm: [5.61, 4.83, 4.93] # FROM 710 acceptance testing at UCL (10cm)
spect_gauss_fwhm: [6.8, 6.8, 6.8] # FROM bremss data anyscan
spect_res: [1.31, 0.027, false] # Analytical collimator resolution for SPECT
use_zoom_registration: false

#== Forward models
no_gpu: false
keep_all_views_in_cache: true
use_tof: false

#== Data paths
pet_data_path: "/home/storage/prepared_data/oxford_patient_data/sirt3/PET"
spect_data_path: "/home/storage/prepared_data/oxford_patient_data/sirt3/SPECT"
output_path: "/home/sam/working/synergistic_recon/output/dtnv_uniform_weighted_overlap_fix_floor_log_tnv"
working_path: "/home/sam/working/synergistic_recon/output"

#== Miscellaneous
save_images: true
save_gradients: true
save_preconditioners: true
seed: null
profile: false
