#== Test/Debug config - Function testing only (no reconstruction)
num_subsets: [9, 12]

#== Regularisation
no_prior: false
use_kappa: true
delta: null

# Modality-specific TV prior settings
use_modality_specific_priors: false
prior: "tv"
gamma_pet: 100.0
gamma_spect: 10.0
tv_stencil: "6"
tv_max_step: 1
directional_tv: true
tv_both_directions: false

# TNV (vectorial) prior settings
use_tnv_prior: true
gamma_tnv: 100.0
alpha: 1.0
beta: 1.0
tnv_stencil: "26"
tnv_max_step: 1
directional_tnv: true
tnv_both_directions: false
tail_singular_values: null
stable: false

#== Image processing
pet_gauss_fwhm: [5.61, 4.83, 4.93]
spect_gauss_fwhm: [6.7, 6.7, 6.7]
spect_res: [0.81, 0.03, false]

#== Forward models
no_gpu: false
stop_keep_all_views_in_cache: true
use_tof: false
use_scatter: true

#== Data paths
pet_data_path: "/home/sporter/synergistic_Y90/prepared_data/oxford_patient_data/sirt3/PET"
spect_data_path: "/home/sporter/synergistic_Y90/prepared_data/oxford_patient_data/sirt3/SPECT"
output_path: "/home/sporter/synergistic_Y90/SETR/output/debug_test"
working_path: "/home/sporter/synergistic_Y90/SETR/tmp"

#== Miscellaneous
save_images: true
seed: null
profile: false
