alpha: 1.0
beta: 1.0
delta: null
num_subsets: [9, 12]
no_prior: false
num_epochs: 30
use_kappa: false
initial_step_size: 0.1
iterations: 250
update_interval: null
relaxation_eta: 0.02
tail_singular_values: null

pet_gauss_fwhm: [5.0, 5.0, 5.0]
spect_gauss_fwhm: [13.4, 13.4, 13.4]
spect_res: [1.22, 0.03, false]

use_tof: false

pet_data_path: "/home/storage/prepared_data/oxford_patient_data/sirt3/PET"
spect_data_path: "/home/storage/prepared_data/oxford_patient_data/sirt3/SPECT"
output_path: "/home/sam/working/synergistic_recon/output/test"
working_path: "/home/sam/working/synergistic_recon/tmp"

save_images: true
seed: null
no_gpu: false
stop_keep_all_views_in_cache: true
profile: false
